In [15]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df_prov = pd.read_parquet(r"output\providers_20250809_155645.parquet")
display(df_prov.head(5))

,provider_group_id,npi,tin_type,tin_value,reporting_entity_name,reporting_entity_type,last_updated_on,version
0,19,1033363064,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0
1,159,1588023998,ein,811272595,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0
2,168,1700899754,ein,201354399,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0
3,612,1194751024,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0
4,612,1417921065,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0

In [16]:
values_to_check = [
    '811272595',
    '300466706',
    '472413464',
    '201354399'
]  # replace with your actual values
filtered_df = df_prov[df_prov['tin_value'].isin(values_to_check)]
print("Filtered DataFrame:")
display(filtered_df.head(5))
print("unique provider_group_id: ", filtered_df['provider_group_id'].unique())
print("unique tins: ", filtered_df['tin_value'].unique())

Filtered DataFrame:

,provider_group_id,npi,tin_type,tin_value,reporting_entity_name,reporting_entity_type,last_updated_on,version
0,19,1033363064,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0
1,159,1588023998,ein,811272595,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0
2,168,1700899754,ein,201354399,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0
3,612,1194751024,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0
4,612,1417921065,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0

unique provider_group_id:  [ 19 159 168 612 686 712 800]
unique tins:  ['300466706' '811272595' '201354399' '472413464']

In [17]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df_rates = pd.read_parquet(r"output\rates_20250810_153112.parquet")
display(df_rates.head(1))
print("# of unique provider_ref_id: ", df_rates['provider_reference_id'].nunique())
print("# of unique billing_codes: ", df_rates['billing_code'].nunique())

,provider_reference_id,negotiated_rate,negotiated_type,billing_class,expiration_date,service_codes,billing_code,billing_code_type,description,name,negotiation_arrangement,reporting_entity_name,reporting_entity_type,last_updated_on,version
0,168,70.12,negotiated,professional,9999-12-31,[],0001A,CPT,Immunization administration by intramuscular i...,IMM ADMN SARSCOV2 30MCG/0.3ML DIL RECON 1ST DOSE,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0

# of unique provider_ref_id:  7
# of unique billing_codes:  16889

In [18]:
merged = filtered_df.merge(df_rates, how='inner', left_on='provider_group_id', right_on='provider_reference_id')
display(merged.head(5))
print("# of unique billing_codes: ", merged['billing_code'].nunique())

,provider_group_id,npi,tin_type,tin_value,reporting_entity_name_x,reporting_entity_type_x,last_updated_on_x,version_x,provider_reference_id,negotiated_rate,negotiated_type,billing_class,expiration_date,service_codes,billing_code,billing_code_type,description,name,negotiation_arrangement,reporting_entity_name_y,reporting_entity_type_y,last_updated_on_y,version_y
0,19,1033363064,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,19,405.0,negotiated,institutional,9999-12-31,"['n', 'u', 'l']",0054T,CPT,Computer-assisted musculoskeletal surgical nav...,CPTR-ASST MUSCSKEL NAVIGJ ORTHO FLUOR IMAGES,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0
1,19,1033363064,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,19,405.0,negotiated,institutional,9999-12-31,"['n', 'u', 'l']",0055T,CPT,Computer-assisted musculoskeletal surgical nav...,CPTR-ASST MUSCSKEL NAVIGJ ORTHO CT/MRI,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0
2,19,1033363064,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,19,1687.0,negotiated,institutional,9999-12-31,"['n', 'u', 'l']",0071T,CPT,Focused ultrasound ablation of uterine leiomyo...,US ABLATJ UTERINE LEIOMYOMATA < 200 CC TISSUE,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0
3,19,1033363064,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,19,1687.0,negotiated,institutional,9999-12-31,"['n', 'u', 'l']",0072T,CPT,Focused ultrasound ablation of uterine leiomyo...,FCSD US ABLTJ UTERINE LEIOMYOMAT >= 200 CC TISS,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0
4,19,1033363064,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,19,730.0,negotiated,institutional,9999-12-31,"['n', 'u', 'l']",0075T,CPT,Transcatheter placement of extracranial verteb...,TCAT PLMT XTRC VRT CRTD STENT RS&I PRQ 1ST VSL,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0

# of unique billing_codes:  16889

In [22]:
merged = df_prov.merge(df_rates, how='inner', left_on='provider_group_id', right_on='provider_reference_id')
display(merged.head(1))
print("number of rows: ", merged.shape[0])
print("unique provider_group_id: ", merged['provider_group_id'].unique())
print("unique billing_codes: ", merged['billing_code'].nunique())
print("unique billing_code_type: ", merged['billing_code_type'].nunique())
print("unique billing_code_type: ", merged['billing_code_type'].unique())

print("unique RC codes: ", merged.loc[merged['billing_code_type'] == 'RC', 'billing_code'].nunique())
print("unique CPT codes: ", merged.loc[merged['billing_code_type'] == 'CPT', 'billing_code'].nunique())
print("unique MS-DRG codes: ", merged.loc[merged['billing_code_type'] == 'MS-DRG', 'billing_code'].nunique())

,provider_group_id,npi,tin_type,tin_value,reporting_entity_name_x,reporting_entity_type_x,last_updated_on_x,version_x,provider_reference_id,negotiated_rate,negotiated_type,billing_class,expiration_date,service_codes,billing_code,billing_code_type,description,name,negotiation_arrangement,reporting_entity_name_y,reporting_entity_type_y,last_updated_on_y,version_y
0,19,1033363064,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,19,405.0,negotiated,institutional,9999-12-31,"['n', 'u', 'l']",0054T,CPT,Computer-assisted musculoskeletal surgical nav...,CPTR-ASST MUSCSKEL NAVIGJ ORTHO FLUOR IMAGES,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0

number of rows:  638815
unique provider_group_id:  [ 19 159 168 612 686 712 800]
unique billing_codes:  16889
unique billing_code_type:  4
unique billing_code_type:  ['CPT' 'RC' 'HCPCS' 'MS-DRG']
unique RC codes:  146
unique CPT codes:  11436
unique MS-DRG codes:  777

In [20]:
nppes_df = pd.read_parquet(r"C:\Users\ChristopherCato\OneDrive - clarity-dx.com\code\bph\tic\nppes_data\nppes_providers.parquet")
display(nppes_df.head(1))

,npi,provider_name,credentials,gender,enumeration_date,last_updated,addresses,primary_specialty,secondary_specialties,provider_type,metadata
0,1699775759,"{'first': 'RAJA', 'last': 'VARMA', 'middle': '...",[MD],M,2005-07-29 00:00:00+00:00,2021-04-22 00:00:00+00:00,"[{'city': 'PATCHOGUE', 'country': 'United Stat...","Internal Medicine, Cardiovascular Disease",[],Individual,"{'api_version': '2.1', 'data_source': 'NPI_Reg..."

In [21]:
joined_df = merged.merge(nppes_df, how='inner', on='npi')
display(joined_df.head(1))
print("# of rows: ", joined_df.shape[0])
print("# of unique billing_codes: ", joined_df['billing_code'].nunique())

,provider_group_id,npi,tin_type,tin_value,reporting_entity_name_x,reporting_entity_type_x,last_updated_on_x,version_x,provider_reference_id,negotiated_rate,negotiated_type,billing_class,expiration_date,service_codes,billing_code,billing_code_type,description,name,negotiation_arrangement,reporting_entity_name_y,reporting_entity_type_y,last_updated_on_y,version_y,provider_name,credentials,gender,enumeration_date,last_updated,addresses,primary_specialty,secondary_specialties,provider_type,metadata
0,168,1700899754,ein,201354399,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,168,70.12,negotiated,professional,9999-12-31,[],0001A,CPT,Immunization administration by intramuscular i...,IMM ADMN SARSCOV2 30MCG/0.3ML DIL RECON 1ST DOSE,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,"{'first': '', 'last': '', 'middle': '', 'suffi...",[],Unknown,2006-08-14 00:00:00+00:00,2022-04-25 00:00:00+00:00,"[{'city': 'ATLANTA', 'country': 'United States...",Physical Medicine & Rehabilitation,"[Physical Medicine & Rehabilitation, Pain Medi...",Organization,"{'api_version': '2.1', 'data_source': 'NPI_Reg..."

# of rows:  632187
# of unique billing_codes:  16886

In [ ]:
import numpy as np
addresses_df = joined_df['addresses'].apply(
    lambda x: x[0] if isinstance(x, (list, np.ndarray)) and len(x) > 0 else {}
).apply(pd.Series)

In [24]:
print("Extracted columns:", addresses_df.columns.tolist())

Extracted columns: ['city', 'country', 'fax', 'phone', 'purpose', 'state', 'street', 'type', 'zip']

In [25]:
addresses_df = addresses_df.rename(columns={'zip': 'full_zip'})

joined_df = pd.concat([joined_df, addresses_df], axis=1)
display(joined_df.head(1))

,provider_group_id,npi,tin_type,tin_value,reporting_entity_name_x,reporting_entity_type_x,last_updated_on_x,version_x,provider_reference_id,negotiated_rate,negotiated_type,billing_class,expiration_date,service_codes,billing_code,billing_code_type,description,name,negotiation_arrangement,reporting_entity_name_y,reporting_entity_type_y,last_updated_on_y,version_y,provider_name,credentials,gender,enumeration_date,last_updated,addresses,primary_specialty,secondary_specialties,provider_type,metadata,city,country,fax,phone,purpose,state,street,type,full_zip
0,186,1932170131,ein,581646537,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,186,78.44,negotiated,professional,9999-12-31,"['02', '05', '06', '07', '08', '19', '21', '22...",20550,CPT,"Injection(s); single tendon sheath, or ligamen...",INJECTION 1 TENDON SHEATH/LIGAMENT APONEUROSIS,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,"{'first': 'MICHAEL', 'last': 'COBB', 'middle':...",[MD],F,2006-01-27 00:00:00+00:00,2024-12-04 00:00:00+00:00,"[{'city': 'EDINA', 'country': 'United States',...","Radiology, Diagnostic Radiology","[Radiology, Diagnostic Radiology, Radiology, D...",Individual,"{'api_version': '2.1', 'data_source': 'NPI_Reg...",EDINA,United States,612-294-4903,952-595-1301,LOCATION,MN,3600 MINNESOTA DR STE 800,DOM,554357915

In [26]:
for i, row in joined_df['addresses'].dropna().head(10).items():
    print(f"Row {i}:")
    print("  Type:", type(row))
    print("  Value:", row)
    if isinstance(row, list) and len(row) > 0:
        print("  First dict keys:", row[0].keys())
        print("  ZIP:", row[0].get('zip'))
    else:
        print("  Skipped - not a list or empty.")
    print("-" * 40)

Row 0:
  Type: <class 'numpy.ndarray'>
  Value: [{'city': 'EDINA', 'country': 'United States', 'fax': '612-294-4903', 'phone': '952-595-1301', 'purpose': 'LOCATION', 'state': 'MN', 'street': '3600 MINNESOTA DR STE 800', 'type': 'DOM', 'zip': '554357915'}]
  Skipped - not a list or empty.
----------------------------------------
Row 1:
  Type: <class 'numpy.ndarray'>
  Value: [{'city': 'EDINA', 'country': 'United States', 'fax': '612-294-4903', 'phone': '952-595-1301', 'purpose': 'LOCATION', 'state': 'MN', 'street': '3600 MINNESOTA DR STE 800', 'type': 'DOM', 'zip': '554357915'}]
  Skipped - not a list or empty.
----------------------------------------
Row 2:
  Type: <class 'numpy.ndarray'>
  Value: [{'city': 'EDINA', 'country': 'United States', 'fax': '612-294-4903', 'phone': '952-595-1301', 'purpose': 'LOCATION', 'state': 'MN', 'street': '3600 MINNESOTA DR STE 800', 'type': 'DOM', 'zip': '554357915'}]
  Skipped - not a list or empty.
----------------------------------------
Row 3:
  Type: <class 'numpy.ndarray'>
  Value: [{'city': 'EDINA', 'country': 'United States', 'fax': '612-294-4903', 'phone': '952-595-1301', 'purpose': 'LOCATION', 'state': 'MN', 'street': '3600 MINNESOTA DR STE 800', 'type': 'DOM', 'zip': '554357915'}]
  Skipped - not a list or empty.
----------------------------------------
Row 4:
  Type: <class 'numpy.ndarray'>
  Value: [{'city': 'EDINA', 'country': 'United States', 'fax': '612-294-4903', 'phone': '952-595-1301', 'purpose': 'LOCATION', 'state': 'MN', 'street': '3600 MINNESOTA DR STE 800', 'type': 'DOM', 'zip': '554357915'}]
  Skipped - not a list or empty.
----------------------------------------
Row 5:
  Type: <class 'numpy.ndarray'>
  Value: [{'city': 'EDINA', 'country': 'United States', 'fax': '612-294-4903', 'phone': '952-595-1301', 'purpose': 'LOCATION', 'state': 'MN', 'street': '3600 MINNESOTA DR STE 800', 'type': 'DOM', 'zip': '554357915'}]
  Skipped - not a list or empty.
----------------------------------------
Row 6:
  Type: <class 'numpy.ndarray'>
  Value: [{'city': 'EDINA', 'country': 'United States', 'fax': '612-294-4903', 'phone': '952-595-1301', 'purpose': 'LOCATION', 'state': 'MN', 'street': '3600 MINNESOTA DR STE 800', 'type': 'DOM', 'zip': '554357915'}]
  Skipped - not a list or empty.
----------------------------------------
Row 7:
  Type: <class 'numpy.ndarray'>
  Value: [{'city': 'EDINA', 'country': 'United States', 'fax': '612-294-4903', 'phone': '952-595-1301', 'purpose': 'LOCATION', 'state': 'MN', 'street': '3600 MINNESOTA DR STE 800', 'type': 'DOM', 'zip': '554357915'}]
  Skipped - not a list or empty.
----------------------------------------
Row 8:
  Type: <class 'numpy.ndarray'>
  Value: [{'city': 'EDINA', 'country': 'United States', 'fax': '612-294-4903', 'phone': '952-595-1301', 'purpose': 'LOCATION', 'state': 'MN', 'street': '3600 MINNESOTA DR STE 800', 'type': 'DOM', 'zip': '554357915'}]
  Skipped - not a list or empty.
----------------------------------------
Row 9:
  Type: <class 'numpy.ndarray'>
  Value: [{'city': 'EDINA', 'country': 'United States', 'fax': '612-294-4903', 'phone': '952-595-1301', 'purpose': 'LOCATION', 'state': 'MN', 'street': '3600 MINNESOTA DR STE 800', 'type': 'DOM', 'zip': '554357915'}]
  Skipped - not a list or empty.
----------------------------------------

In [27]:
joined_df['zip5'] = joined_df['full_zip'].astype(str).str[:5]

In [28]:
display(joined_df.head(1))

,provider_group_id,npi,tin_type,tin_value,reporting_entity_name_x,reporting_entity_type_x,last_updated_on_x,version_x,provider_reference_id,negotiated_rate,negotiated_type,billing_class,expiration_date,service_codes,billing_code,billing_code_type,description,name,negotiation_arrangement,reporting_entity_name_y,reporting_entity_type_y,last_updated_on_y,version_y,provider_name,credentials,gender,enumeration_date,last_updated,addresses,primary_specialty,secondary_specialties,provider_type,metadata,city,country,fax,phone,purpose,state,street,type,full_zip,zip5
0,186,1932170131,ein,581646537,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,186,78.44,negotiated,professional,9999-12-31,"['02', '05', '06', '07', '08', '19', '21', '22...",20550,CPT,"Injection(s); single tendon sheath, or ligamen...",INJECTION 1 TENDON SHEATH/LIGAMENT APONEUROSIS,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,"{'first': 'MICHAEL', 'last': 'COBB', 'middle':...",[MD],F,2006-01-27 00:00:00+00:00,2024-12-04 00:00:00+00:00,"[{'city': 'EDINA', 'country': 'United States',...","Radiology, Diagnostic Radiology","[Radiology, Diagnostic Radiology, Radiology, D...",Individual,"{'api_version': '2.1', 'data_source': 'NPI_Reg...",EDINA,United States,612-294-4903,952-595-1301,LOCATION,MN,3600 MINNESOTA DR STE 800,DOM,554357915,55435

walk in zip to cbsa code xwalk

In [ ]:
# replace the path with wherever your .xlsx lives
zip_xwalk = pd.read_excel(r"scripts\ZIP_CBSA_062025.xlsx", 
                            # or whatever sheet you need
                          engine='openpyxl',
                          converters={'ZIP': lambda x: str(x).zfill(5)},)     # necessary if you haven’t installed xlrd >2.0

# inspect the first few rows
zip_xwalk.head()

,ZIP,CBSA,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
0,00501,35620,HOLTSVILLE,NY,0.000000,1.000000,0.000000,1.000000
1,00601,99999,ADJUNTAS,PR,0.997452,0.994937,0.987805,0.997052
2,00601,29720,ADJUNTAS,PR,0.002548,0.005063,0.012195,0.002948
3,00602,10380,AGUADA,PR,1.000000,1.000000,1.000000,1.000000
4,00603,10380,AGUADILLA,PR,1.000000,1.000000,1.000000,1.000000

walk in cbsa title to cbsa code xlsx

In [ ]:
# replace the path with wherever your .xlsx lives
cbsa_xwalk = pd.read_excel(r"scripts\cbsa_codes.xlsx", 
                            # or whatever sheet you need
                          engine='openpyxl')     # necessary if you haven’t installed xlrd >2.0

# inspect the first few rows
cbsa_xwalk.head()

,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
0,10100,NaN,NaN,"Aberdeen, SD",Micropolitan Statistical Area,NaN,NaN,Brown County,South Dakota,46,13,Central
1,10100,NaN,NaN,"Aberdeen, SD",Micropolitan Statistical Area,NaN,NaN,Edmunds County,South Dakota,46,45,Outlying
2,10140,NaN,NaN,"Aberdeen, WA",Micropolitan Statistical Area,NaN,NaN,Grays Harbor County,Washington,53,27,Central
3,10180,NaN,101.0,"Abilene, TX",Metropolitan Statistical Area,NaN,"Abilene-Sweetwater, TX",Callahan County,Texas,48,59,Outlying
4,10180,NaN,101.0,"Abilene, TX",Metropolitan Statistical Area,NaN,"Abilene-Sweetwater, TX",Jones County,Texas,48,253,Outlying

merge the two cbsa files

In [31]:
merged_cbsa = pd.merge(zip_xwalk, cbsa_xwalk, left_on='CBSA', right_on='CBSA Code', how='inner')
merged_cbsa.head()

,ZIP,CBSA,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
0,00501,35620,HOLTSVILLE,NY,0.0,1.0,0.0,1.0,35620,29484.0,408.0,"New York-Newark-Jersey City, NY-NJ",Metropolitan Statistical Area,"Lakewood-New Brunswick, NJ","New York-Newark, NY-NJ-CT-PA",Middlesex County,New Jersey,34,23,Central
1,00501,35620,HOLTSVILLE,NY,0.0,1.0,0.0,1.0,35620,29484.0,408.0,"New York-Newark-Jersey City, NY-NJ",Metropolitan Statistical Area,"Lakewood-New Brunswick, NJ","New York-Newark, NY-NJ-CT-PA",Monmouth County,New Jersey,34,25,Central
2,00501,35620,HOLTSVILLE,NY,0.0,1.0,0.0,1.0,35620,29484.0,408.0,"New York-Newark-Jersey City, NY-NJ",Metropolitan Statistical Area,"Lakewood-New Brunswick, NJ","New York-Newark, NY-NJ-CT-PA",Ocean County,New Jersey,34,29,Central
3,00501,35620,HOLTSVILLE,NY,0.0,1.0,0.0,1.0,35620,29484.0,408.0,"New York-Newark-Jersey City, NY-NJ",Metropolitan Statistical Area,"Lakewood-New Brunswick, NJ","New York-Newark, NY-NJ-CT-PA",Somerset County,New Jersey,34,35,Central
4,00501,35620,HOLTSVILLE,NY,0.0,1.0,0.0,1.0,35620,35004.0,408.0,"New York-Newark-Jersey City, NY-NJ",Metropolitan Statistical Area,"Nassau County-Suffolk County, NY","New York-Newark, NY-NJ-CT-PA",Nassau County,New York,36,59,Central

join the cbsa to fact table

In [32]:
fact_table = pd.merge(
    joined_df,
    merged_cbsa,
    left_on='zip5',
    right_on='ZIP',
    how='left',
    suffixes=('_l','_r')
)
fact_table.head(1)

,provider_group_id,npi,tin_type,tin_value,reporting_entity_name_x,reporting_entity_type_x,last_updated_on_x,version_x,provider_reference_id,negotiated_rate,negotiated_type,billing_class,expiration_date,service_codes,billing_code,billing_code_type,description,name,negotiation_arrangement,reporting_entity_name_y,reporting_entity_type_y,last_updated_on_y,version_y,provider_name,credentials,gender,enumeration_date,last_updated,addresses,primary_specialty,secondary_specialties,provider_type,metadata,city,country,fax,phone,purpose,state,street,type,full_zip,zip5,ZIP,CBSA,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
0,186,1932170131,ein,581646537,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,186,78.44,negotiated,professional,9999-12-31,"['02', '05', '06', '07', '08', '19', '21', '22...",20550,CPT,"Injection(s); single tendon sheath, or ligamen...",INJECTION 1 TENDON SHEATH/LIGAMENT APONEUROSIS,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,"{'first': 'MICHAEL', 'last': 'COBB', 'middle':...",[MD],F,2006-01-27 00:00:00+00:00,2024-12-04 00:00:00+00:00,"[{'city': 'EDINA', 'country': 'United States',...","Radiology, Diagnostic Radiology","[Radiology, Diagnostic Radiology, Radiology, D...",Individual,"{'api_version': '2.1', 'data_source': 'NPI_Reg...",EDINA,United States,612-294-4903,952-595-1301,LOCATION,MN,3600 MINNESOTA DR STE 800,DOM,554357915,55435,55435,33460.0,MINNEAPOLIS,MN,1.0,1.0,1.0,1.0,33460.0,NaN,378.0,"Minneapolis-St. Paul-Bloomington, MN-WI",Metropolitan Statistical Area,NaN,"Minneapolis-St. Paul, MN-WI",Anoka County,Minnesota,27.0,3.0,Central

In [33]:
target_tins = ['581646537', '300466706']  # replace with your actual values
ga_fact_table_tins = fact_table[fact_table['tin_value'].isin(target_tins)]

In [34]:
# Remove duplicate columns by keeping the first occurrence
ga_fact_table_tins = ga_fact_table_tins.loc[:, ~ga_fact_table_tins.columns.duplicated()]

In [35]:
ga_fact_table_tins_cleaned = ga_fact_table_tins[ga_fact_table_tins['state'] == 'GA']
display(ga_fact_table_tins_cleaned.head(1))
print("unique CBSA Title: ", ga_fact_table_tins_cleaned['CBSA Title'].unique())

,provider_group_id,npi,tin_type,tin_value,reporting_entity_name_x,reporting_entity_type_x,last_updated_on_x,version_x,provider_reference_id,negotiated_rate,negotiated_type,billing_class,expiration_date,service_codes,billing_code,billing_code_type,description,name,negotiation_arrangement,reporting_entity_name_y,reporting_entity_type_y,last_updated_on_y,version_y,provider_name,credentials,gender,enumeration_date,last_updated,addresses,primary_specialty,secondary_specialties,provider_type,metadata,city,country,fax,phone,purpose,state,street,type,full_zip,zip5,ZIP,CBSA,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
8295,612,1194751024,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,612,68.21,negotiated,professional,9999-12-31,"['02', '05', '06', '07', '08', '19', '21', '22...",20550,CPT,"Injection(s); single tendon sheath, or ligamen...",INJECTION 1 TENDON SHEATH/LIGAMENT APONEUROSIS,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,"{'first': 'RUBEN', 'last': 'DIAZ', 'middle': '...",[MD],M,2006-06-23 00:00:00+00:00,2024-01-10 00:00:00+00:00,"[{'city': 'SAVANNAH', 'country': 'United State...",Physical Medicine & Rehabilitation,"[Physical Medicine & Rehabilitation, Pain Medi...",Individual,"{'api_version': '2.1', 'data_source': 'NPI_Reg...",SAVANNAH,United States,,912-721-2262,LOCATION,GA,322 STEPHENSON AVE STE A,DOM,314054345,31405,31405,42340.0,SAVANNAH,GA,1.0,1.0,1.0,1.0,42340.0,NaN,496.0,"Savannah, GA",Metropolitan Statistical Area,NaN,"Savannah-Hinesville-Statesboro, GA",Bryan County,Georgia,13.0,29.0,Central

unique CBSA Title:  ['Savannah, GA' 'Jesup, GA' 'Macon-Bibb County, GA' 'Dublin, GA'
 'Statesboro, GA' 'Vidalia, GA' nan]

inspect GA

In [36]:
ga_fact_table = fact_table[fact_table['state'] == 'GA']
target_tins = ['581646537', '300466706']  # replace with your actual values
ga_fact_table_tins = ga_fact_table[ga_fact_table['tin_value'].isin(target_tins)]
display(ga_fact_table.head(1))
display(ga_fact_table_tins.head(1))

print("unique billing_code: ", ga_fact_table_tins['billing_code'].unique())
print("unique tin_values: ", ga_fact_table_tins['tin_value'].unique())

,provider_group_id,npi,tin_type,tin_value,reporting_entity_name_x,reporting_entity_type_x,last_updated_on_x,version_x,provider_reference_id,negotiated_rate,negotiated_type,billing_class,expiration_date,service_codes,billing_code,billing_code_type,description,name,negotiation_arrangement,reporting_entity_name_y,reporting_entity_type_y,last_updated_on_y,version_y,provider_name,credentials,gender,enumeration_date,last_updated,addresses,primary_specialty,secondary_specialties,provider_type,metadata,city,country,fax,phone,purpose,state,street,type,full_zip,zip5,ZIP,CBSA,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
8295,612,1194751024,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,612,68.21,negotiated,professional,9999-12-31,"['02', '05', '06', '07', '08', '19', '21', '22...",20550,CPT,"Injection(s); single tendon sheath, or ligamen...",INJECTION 1 TENDON SHEATH/LIGAMENT APONEUROSIS,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,"{'first': 'RUBEN', 'last': 'DIAZ', 'middle': '...",[MD],M,2006-06-23 00:00:00+00:00,2024-01-10 00:00:00+00:00,"[{'city': 'SAVANNAH', 'country': 'United State...",Physical Medicine & Rehabilitation,"[Physical Medicine & Rehabilitation, Pain Medi...",Individual,"{'api_version': '2.1', 'data_source': 'NPI_Reg...",SAVANNAH,United States,,912-721-2262,LOCATION,GA,322 STEPHENSON AVE STE A,DOM,314054345,31405,31405,42340.0,SAVANNAH,GA,1.0,1.0,1.0,1.0,42340.0,NaN,496.0,"Savannah, GA",Metropolitan Statistical Area,NaN,"Savannah-Hinesville-Statesboro, GA",Bryan County,Georgia,13.0,29.0,Central

,provider_group_id,npi,tin_type,tin_value,reporting_entity_name_x,reporting_entity_type_x,last_updated_on_x,version_x,provider_reference_id,negotiated_rate,negotiated_type,billing_class,expiration_date,service_codes,billing_code,billing_code_type,description,name,negotiation_arrangement,reporting_entity_name_y,reporting_entity_type_y,last_updated_on_y,version_y,provider_name,credentials,gender,enumeration_date,last_updated,addresses,primary_specialty,secondary_specialties,provider_type,metadata,city,country,fax,phone,purpose,state,street,type,full_zip,zip5,ZIP,CBSA,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
8295,612,1194751024,ein,300466706,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,612,68.21,negotiated,professional,9999-12-31,"['02', '05', '06', '07', '08', '19', '21', '22...",20550,CPT,"Injection(s); single tendon sheath, or ligamen...",INJECTION 1 TENDON SHEATH/LIGAMENT APONEUROSIS,ffs,UnitedHealthcare of Georgia Inc.,Insurer,2025-08-01,1.0.0,"{'first': 'RUBEN', 'last': 'DIAZ', 'middle': '...",[MD],M,2006-06-23 00:00:00+00:00,2024-01-10 00:00:00+00:00,"[{'city': 'SAVANNAH', 'country': 'United State...",Physical Medicine & Rehabilitation,"[Physical Medicine & Rehabilitation, Pain Medi...",Individual,"{'api_version': '2.1', 'data_source': 'NPI_Reg...",SAVANNAH,United States,,912-721-2262,LOCATION,GA,322 STEPHENSON AVE STE A,DOM,314054345,31405,31405,42340.0,SAVANNAH,GA,1.0,1.0,1.0,1.0,42340.0,NaN,496.0,"Savannah, GA",Metropolitan Statistical Area,NaN,"Savannah-Hinesville-Statesboro, GA",Bryan County,Georgia,13.0,29.0,Central

unique billing_code:  ['20550' '20551' '20552' '20553' '20600' '20605' '20610' '20611' '23410'
 '23412' '23430' '23472' '24341' '25310' '26055' '27096' '27130' '27427'
 '27447' '27507' '27514' '27650' '27786' '29806' '29807' '29823' '29826'
 '29827' '29828' '29881' '29888' '62321' '62323' '64483' '64484' '64490'
 '64493' '64633' '64635' '70030' '70100' '70110' '70120' '70130' '70134'
 '70140' '70150' '70160' '70190' '70200' '70210' '70220' '70240' '70250'
 '70260' '70328' '70330' '70336' '70360' '70370' '70450' '70460' '70470'
 '70480' '70481' '70482' '70486' '70487' '70488' '70490' '70491' '70492'
 '70540' '70542' '70543' '70544' '70551' '70552' '70553' '71046' '71100'
 '71101' '71110' '71111' '71120' '71130' '71250' '71260' '71270' '71275'
 '71550' '71551' '71552' '72020' '72040' '72050' '72052' '72070' '72072'
 '72074' '72080' '72082' '72083' '72084' '72100' '72110' '72114' '72120'
 '72125' '72126' '72127' '72128' '72129' '72130' '72131' '72132' '72133'
 '72141' '72142' '72146' '72147' '72148' '72149' '72156' '72157' '72158'
 '72170' '72190' '72192' '72193' '72194' '72195' '72196' '72197' '72200'
 '72202' '72220' '73000' '73010' '73020' '73030' '73040' '73050' '73060'
 '73070' '73080' '73090' '73092' '73100' '73110' '73120' '73130' '73140'
 '73200' '73201' '73202' '73218' '73219' '73220' '73221' '73222' '73223'
 '73501' '73502' '73503' '73521' '73522' '73523' '73525' '73551' '73552'
 '73560' '73562' '73564' '73565' '73580' '73590' '73592' '73600' '73610'
 '73620' '73630' '73650' '73660' '73700' '73701' '73702' '73718' '73719'
 '73720' '73721' '73722' '73723' '74150' '74160' '74170' '74176' '74177'
 '74178' '74181' '74182' '74183' '74220' '74240' '74246']
unique tin_values:  ['300466706']

In [37]:
for col in ga_fact_table_tins_cleaned.columns:
    if pd.api.types.is_datetime64tz_dtype(ga_fact_table_tins_cleaned[col]):
        print(f"Converting timezone-aware column: {col}")
        ga_fact_table_tins_cleaned[col] = ga_fact_table_tins_cleaned[col].dt.tz_localize(None)


ga_fact_table_tins_cleaned.to_excel("GA_UHC.xlsx", index=True)

C:\Users\ChristopherCato\AppData\Local\Temp\ipykernel_24712\195964233.py:2: DeprecationWarning: is_datetime64tz_dtype is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.DatetimeTZDtype)` instead.
  if pd.api.types.is_datetime64tz_dtype(ga_fact_table_tins_cleaned[col]):

Converting timezone-aware column: enumeration_date
Converting timezone-aware column: last_updated